# Generated by Django 3.1.2 on 2020-11-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
