# Generated by Django 3.1.2 on 2020-10-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='class',
            managers=[
            ],
        ),
    ]
