# Generated by Django 3.1.2 on 2020-11-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20201031_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='content',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='content',
            new_name='desc',
        ),
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='quiz-files'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='quiz-files'),
        ),
    ]
