# Generated by Django 3.1.2 on 2020-12-23 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entCell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entvideo',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
