# Generated by Django 3.1.2 on 2020-12-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entCell', '0002_entvideo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='entNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=280)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
